name: "CI"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  schedule:
    - cron: "37 13 * * 1"

jobs:
  tests:
    name: "Run tests"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        php-version: # https://www.php.net/supported-versions.php
          - "8.1"
          - "8.2"
          - "8.3"
        symfony-version: # https://symfony.com/releases
          - "4.4.20"
          - "5.3"
          - "5.4"
          - "6.3"
          - "6.4"
          - "7.0"
        exclude:
          # Symfony 7 requires PHP 8.2+
          -   php-version: '8.1'
              symfony-version: '7.0'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          tools: "flex"
        env:
          fail-fast: true
      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict --no-interaction --ansi"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"
      - name: "Run tests"
        run: "make test"

  check-coding-standards:
    name: "Check coding standards"
    uses: "broadway/github-actions/.github/workflows/check-coding-standards.yml@main"

  static-analysis:
    name: "Static analysis"
    runs-on: "ubuntu-20.04"
    continue-on-error: true
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          coverage: "none"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
      - name: "Run PHPStan"
        run: "make phpstan"
